# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0002_auto_20180721_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20, verbose_name='省市')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('address', models.CharField(max_length=250, verbose_name='街道地址')),
                ('name', models.CharField(max_length=50, verbose_name='收货人')),
                ('tel', models.IntegerField(verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('paid', models.BooleanField(default=False, verbose_name='是否付款')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='所在订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product', verbose_name='商品')),
            ],
        ),
    ]
